[package]
name = "tx3c"
publish.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
keywords.workspace = true
documentation.workspace = true
homepage.workspace = true
readme.workspace = true

[dependencies]
tx3-tir = { path = "../../crates/tx3-tir" }
tx3-lang = { path = "../../crates/tx3-lang" }
tx3-cardano = { path = "../../crates/tx3-cardano" }
clap = { version = "4.5", features = ["derive"] }
hex = { workspace = true }
serde_json = "1.0.137"
serde.workspace = true
schemars = { version = "1.1.0", features = ["derive"] }
anyhow = "1.0.100"
dotenv-parser = "0.1.3"
